const category = {
  Technology: [
    "Mobile Development",
    "AI / Machine Learning",
    "Cybersecurity",
    "Cloud Computing",
    "DevOps",
    "Open Source",
    "Programming Languages",
    "Databases",
    "Game Development",
  ],
  Education: [
    "Tutorials",
    "Career Guidance",
    "Coding Practice",
    "Interview Preparation",
    "Certifications",
    "Study Notes",
    "College Life",
    "Research",
  ],
  Entertainment: [
    "Movies",
    "TV Shows",
    "Anime",
    "Memes",
    "Music",
    "Celebrity News",
    "Gaming Streams",
  ],
  Gaming: [
    "PC Gaming",
    "Mobile Gaming",
    "Console Gaming",
    "eSports",
    "Walkthroughs",
    "Game Reviews",
    "Game Clips",
  ],
  Business: [
    "Startups",
    "Entrepreneurship",
    "Marketing",
    "Finance",
    "Investing",
    "Freelancing",
    "Remote Work",
  ],
  Lifestyle: [
    "Fashion",
    "Travel",
    "Food",
    "Relationships",
    "Productivity",
    "Home Decor",
  ],
  HealthFitness: [
    "Workout",
    "Nutrition",
    "Mental Health",
    "Yoga",
    "Bodybuilding",
    "Running",
  ],
  Sports: ["Cricket", "Football", "Basketball", "Tennis", "WWE", "Formula 1"],
  Social: [
    "Opinions",
    "Discussions",
    "Confessions",
    "Stories",
    "Polls",
    "Community Questions",
  ],
  Creative: [
    "Photography",
    "Writing",
    "UI/UX Design",
    "Drawing",
    "Video Editing",
    "Animation",
  ],
  News: [
    "World News",
    "Politics",
    "Technology News",
    "Sports News",
    "Local News",
  ],
};

const mainCategorys = [
  "Technology",
  "Education",
  "Entertainment",
  "Gaming",
  "Business",
  "Lifestyle",
  "HealthFitness",
  "Sports",
  "Social",
  "Creative",
  "News",
  "World News",
  "Politics",
  "Technology News",
  "Sports News",
  "Local News",
  "Photography",
  "Writing",
  "UI/UX Design",
  "Drawing",
  "Video Editing",
  "Animation",
  "Opinions",
  "Discussions",
  "Confessions",
  "Stories",
  "Polls",
  "Community Questions",
  "Cricket",
  "Football",
  "Basketball",
  "Tennis",
  "WWE",
  "Formula 1",
  "Workout",
  "Nutrition",
  "Mental Health",
  "Yoga",
  "Bodybuilding",
  "Running",
  "Mobile Development",
  "AI / Machine Learning",
  "Cybersecurity",
  "Cloud Computing",
  "DevOps",
  "Open Source",
  "Programming Languages",
  "Databases",
  "Game Development",
  "Tutorials",
  "Career Guidance",
  "Coding Practice",
  "Interview Preparation",
  "Certifications",
  "Study Notes",
  "College Life",
  "Research",
  "Movies",
  "TV Shows",
  "Anime",
  "Memes",
  "Music",
  "Celebrity News",
  "Gaming Streams",
  "PC Gaming",
  "Mobile Gaming",
  "Console Gaming",
  "eSports",
  "Walkthroughs",
  "Game Reviews",
  "Game Clips",
  "Startups",
  "Entrepreneurship",
  "Marketing",
  "Finance",
  "Investing",
  "Freelancing",
  "Remote Work",
  "Fashion",
  "Travel",
  "Food",
  "Relationships",
  "Productivity",
  "Home Decor",
  "General"
];

module.exports = {mainCategorys, category}
